agent:
  image:
    repository: acuvity/openai-sdk-demo-agent
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 8300
  serviceType: ClusterIP
  corsOrigins: "*"
  config:
    agentModel: "claude-sonnet-4-6"
  mcpServers:
    - name: mcp-server-sequential-thinking2
      description: Sequential thinking MCP server
      url: "http://mcp-server-sequential-thinking.openai-sdk-demo.svc.cluster.local:8000/sse"
    - name: mcp-server-brave-search2
      description: Brave search MCP server
      url: "http://mcp-server-brave-search.openai-sdk-demo.svc.cluster.local:8000/sse"
  otel:
    enabled: true
    serviceName: "openai-sdk-demo-tracer"
    sendSpans: true
    consoleExport: true
    noFileExport: true
    file: "trace.log"
    otlpEndpoint: "http://127.0.0.1:4317"
    insecure: true

ui:
  image:
    repository: acuvity/openai-sdk-demo-ui
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 5174
  serviceType: ClusterIP
  backendUrl: "http://openai-sdk-demo-svc.openai-sdk-demo.svc.cluster.local"

proxy:
  host: "ais-demo-gw.proofpoint-ais.svc.cluster.local"
  httpsPort: 443
  httpPort: 8080

caBundle:
  enabled: false

secrets:
  anthropicApiKey: ""
  braveApiKey: ""
  agentToken: ""


