apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mcpLocal.deploymentName }}
  labels:
    app: {{ .Values.mcpLocal.deploymentName }}
    type: mcp-tool
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mcpLocal.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.mcpLocal.deploymentName }}
    type: mcp-tool
