# yaml-language-server: $schema=../../../pkgs/api/backend/jsonschema/import.json

label: apps-v2/g-adk-demo

apps:
  - name: g-adk-demo
    description: "Google ADK agent application using Google ADK."
    namespace: ./apps/development
    subject:
      - - "@source:namespace=/orgs/acuvity.ai"
      - - "@source:namespace=/"
        - "@source:name=app-tokens"
        - "@source:type=mtls"
        - "@apptoken:name=apex-agent"
    tracing: Recording
    otelReceivers:
      - endpoint: "127.0.0.1:4317"
        protocol: GRPC
      - endpoint: "127.0.0.1:4318"
        protocol: HTTP
    selector:
      type: Kubernetes
      kubernetes:
        kubernetesNamespace: g-adk-demo
    components:
      - name: ui
        description: "The UI running a React application."
        kind: Other
        selector:
          type: Kubernetes
          kubernetes:
            name: g-adk-demo-ui
            kubernetesNamespace: g-adk-demo
            type: Deployment
        ingress:
          defaultACLAction: Allow
          ACLs:
            - name: allow-all-external
              IPRanges:
                - "0.0.0.0/0"
              port: 80
              description: "Allow all external requests"
              action: Allow
        egress:
          defaultPolicy:
            ACLAction: Allow
      - name: agent
        description: "The agent running the API server."
        kind: Agent
        selector:
          type: Kubernetes
          kubernetes:
            name: g-adk-demo
            kubernetesNamespace: g-adk-demo
            type: Deployment
        ingress:
          defaultACLAction: Allow
          ACLs:
            - name: allow-all-external
              IPRanges:
                - "0.0.0.0/0"
              port: 80
              description: "Allow all external requests"
              action: Allow
          listeners:
            - port: 8300
              mode: Proxy
              hosts:
                - g-adk-demo-svc
                - g-adk-demo-svc.g-adk-demo
                - g-adk-demo-svc.g-adk-demo.svc.cluster.local
              extractors:
                - def:
                    name: chat/request/message
                    type: Input
                    path: "/send"
                    method: Post
                    script: |-
                      function extract()
                        body = json.decode(input.body())
                        return {
                          extractions = { content = body.message },
                        }
                      end
                - def:
                    name: chat/response/message
                    type: Output
                    path: "/send"
                    method: Post
                    script: |-
                      function extract()
                        body = json.decode(input.body())
                        return {
                          extractions = { content = body.output },
                        }
                      end
              proxy:
                listenTLS: Disabled
                dialTLS: Disabled
                defaultPolicyAction: Allow
                policies:
                  - name: allow-all-external
                    description: "Allow all external requests"
                    rules:
                      - action: Allow
                        IPRanges:
                          - "0.0.0.0/0"
        egress:
          defaultPolicy:
            ACLAction: Allow
          policies:
            - name: allow-exa-mcp
              description: "Allow requests to Exa MCP search"
              ACLs:
                - action: Allow
                  hostnames:
                    - "mcp.exa.ai"
            - name: allow-mcp-tools
              description: "Allow requests to MCP tools"
              rules:
                - mode: Proxy
                  proxyAction: Allow
                  appComponents:
                    - "g-adk-demo/mcp-sequential-thinking"
                    - "g-adk-demo/mcp-brave-search"
            - name: allow-anthropic
              description: "Allow requests to Anthropic API"
              rules:
                - mode: Proxy
                  proxyAction: Allow
                  providers:
                  - anthropic-api
      - name: mcp-sequential-thinking
        description: "MCP Server: Sequential Thinking"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-sequential-thinking
            kubernetesNamespace: g-adk-demo
            type: Deployment
        ingress:
          listeners:
            - port: 8000
              mode: Proxy
              hosts:
                - mcp-server-sequential-thinking.g-adk-demo.svc.cluster.local
                - mcp-server-sequential-thinking.g-adk-demo
                - mcp-server-sequential-thinking
              extractors:
                - ref: mcp/input
                - ref: mcp/output
              proxy:
                listenTLS: Disabled
                dialTLS: Disabled
                defaultPolicyAction: Allow
                policies:
                  - name: allow-agent
                    description: "Allow requests from the agent"
                    rules:
                      - action: Allow
                        appComponents:
                          - "g-adk-demo/agent"
        egress:
          defaultPolicy:
            ACLAction: Allow
      - name: mcp-brave-search
        description: "MCP Server: Brave Search"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-brave-search
            kubernetesNamespace: g-adk-demo
            type: Deployment
        ingress:
          listeners:
            - port: 8000
              mode: Proxy
              hosts:
                - mcp-server-brave-search.g-adk-demo.svc.cluster.local
                - mcp-server-brave-search.g-adk-demo
                - mcp-server-brave-search
              extractors:
                - ref: mcp/input
                - ref: mcp/output
              proxy:
                listenTLS: Disabled
                dialTLS: Disabled
                defaultPolicyAction: Allow
                policies:
                  - name: allow-agent
                    description: "Allow requests from the agent"
                    rules:
                      - action: Allow
                        appComponents:
                          - "g-adk-demo/agent"
        egress:
          defaultPolicy:
            ACLAction: Allow
          policies:
            - name: allow-brave-search-api
              description: "Allow requests to Brave Search API"
              ACLs:
                - action: Allow
                  hostnames:
                    - "api.search.brave.com"