apiVersion: v1
kind: Service
metadata:
  name: langgraph-demo-svc
spec:
  selector:
    app: langgraph-demo
  ports:
    - port: 80
      targetPort: {{ .Values.agent.port }}
  type:  {{ .Values.agent.serviceType }}
