apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
type: Opaque
stringData:
  ANTHROPIC_API_KEY: {{ required "secrets.anthropicApiKey is required" .Values.secrets.anthropicApiKey | quote }}
  BRAVE_API_KEY: {{ .Values.secrets.braveApiKey | default "" | quote }}
  config.yaml: |
    app_name: langgraph-demo
    title: Langgraph
    cors_origins: {{ .Values.agent.corsOrigins | quote }}
    instruction: You are a research assistant that can search the web and read from a database
    tools:
    mcp_servers:
    {{- range .Values.agent.mcpServers }}
      - name: {{ .name }}
        description: {{ .description }}
        url: {{ .url }}
    {{- end }}
    otel:
      enabled: {{ .Values.agent.otel.enabled }}
      service_name: {{ .Values.agent.otel.serviceName }}
      send_spans: {{ .Values.agent.otel.sendSpans }}
      console_export: {{ .Values.agent.otel.consoleExport }}
      no_file_export: {{ .Values.agent.otel.noFileExport }}
      file: {{ .Values.agent.otel.file }}
      otlp_endpoint: {{ .Values.agent.otel.otlpEndpoint }}
      insecure: {{ .Values.agent.otel.insecure }}