# yaml-language-server: $schema=https://api.acuvity.us/api/v1/jsonschema/import.json

label: apps-v2/openai-mcp-demo

apps:
  - name: openai-mcp-demo
    description: "An example agentic demo application which uses MCP tools"
    subject:
      - - "@source:namespace=/"
        - "@org=acuvity.ai"
    tracing: Recording
    selector:
      type: Kubernetes
      kubernetes:
        kubernetesNamespace: mcp-demo
    components:
      - name: ui
        description: "The UI running a react application."
        kind: Other
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-demo-ui
            kubernetesNamespace: mcp-demo
            type: Deployment
        egress:
          defaultPolicyAction: Allow
      - name: agent
        description: "The agent running the API server."
        kind: Agent
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-demo-agent
            kubernetesNamespace: mcp-demo
            type: Deployment
        provider:
          category: App
          providerType: "LLM"
          hosts:
            - localhost
            - 127.0.0.1
            - mcp-demo-agent.mcp-demo.svc.cluster.local
            - mcp-demo-agent.mcp-demo
            - mcp-demo-agent
          extractors:
            - def:
                name: chat/request/message
                type: Input
                path: "/api/v1/chat"
                method: Post
                script: |-
                  function extract()
                    body = json.decode(input.body())
                    return {
                      annotations = { conversation_id = body.conversation_id },
                      extractions = { content = body.message },
                    }
                  end
            - def:
                name: chat/response/message
                type: Output
                path: "/api/v1/chat"
                method: Post
                script: |-
                  function extract()
                    body = json.decode(input.body())
                    return {
                      annotations = { conversation_id = body.conversation_id },
                      extractions = { content = body.message },
                    }
                  end
        egress:
          defaultPolicyAction: Allow

      - name: mcp-brave-search
        description: "MCP Server: Brave Search"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-brave-search
            kubernetesNamespace: mcp-demo
            type: Deployment
        provider:
          category: App
          providerType: "MCPServer"
          hosts:
            - mcp-server-brave-search.mcp-demo.svc.cluster.local
            - mcp-server-brave-search.mcp-demo
            - mcp-server-brave-search
          extractors:
            - ref: mcp/input-sse
            - ref: mcp/output-sse
            - ref: mcp/input-http
            - ref: mcp/output-http
            - ref: mcp/output-http-get
          proxy:
            listenTLS: Disabled
            dialTLS: Disabled
            defaultPolicyAction: Deny
            policies:
              - name: allow-agent
                description: "Allow requests from the agent"
                rules:
                  - action: Allow
                    appComponents:
                      - "openai-mcp-demo/agent"
        egress:
          defaultPolicyAction: Allow
      - name: mcp-fetch
        description: "MCP Server: Fetch"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-fetch
            kubernetesNamespace: mcp-demo
            type: Deployment
        provider:
          category: App
          providerType: "MCPServer"
          hosts:
            - mcp-server-fetch.mcp-demo.svc.cluster.local
            - mcp-server-fetch.mcp-demo
            - mcp-server-fetch
          extractors:
            - ref: mcp/input-sse
            - ref: mcp/output-sse
            - ref: mcp/input-http
            - ref: mcp/output-http
            - ref: mcp/output-http-get
          proxy:
            listenTLS: Disabled
            dialTLS: Disabled
            defaultPolicyAction: Deny
            policies:
              - name: allow-agent
                description: "Allow requests from the agent"
                rules:
                  - action: Allow
                    appComponents:
                      - "openai-mcp-demo/agent"
        egress:
          defaultPolicyAction: Allow
      - name: mcp-memory
        description: "MCP Server: Memory"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-memory
            kubernetesNamespace: mcp-demo
            type: StatefulSet
        provider:
          category: App
          providerType: "MCPServer"
          hosts:
            - mcp-server-memory.mcp-demo.svc.cluster.local
            - mcp-server-memory.mcp-demo
            - mcp-server-memory
          extractors:
            - ref: mcp/input-sse
            - ref: mcp/output-sse
            - ref: mcp/input-http
            - ref: mcp/output-http
            - ref: mcp/output-http-get
          proxy:
            listenTLS: Disabled
            dialTLS: Disabled
            defaultPolicyAction: Deny
            policies:
              - name: allow-agent
                description: "Allow requests from the agent"
                rules:
                  - action: Allow
                    appComponents:
                      - "openai-mcp-demo/agent"
        egress:
          defaultPolicyAction: Allow
      - name: mcp-sequential-thinking
        description: "MCP Server: Sequential Thinking"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-sequential-thinking
            kubernetesNamespace: mcp-demo
            type: Deployment
        provider:
          category: App
          providerType: "MCPServer"
          hosts:
            - mcp-server-sequential-thinking.mcp-demo.svc.cluster.local
            - mcp-server-sequential-thinking.mcp-demo
            - mcp-server-sequential-thinking
          extractors:
            - ref: mcp/input-sse
            - ref: mcp/output-sse
            - ref: mcp/input-http
            - ref: mcp/output-http
            - ref: mcp/output-http-get
          proxy:
            listenTLS: Disabled
            dialTLS: Disabled
            defaultPolicyAction: Deny
            policies:
              - name: allow-agent
                description: "Allow requests from the agent"
                rules:
                  - action: Allow
                    appComponents:
                      - "openai-mcp-demo/agent"
        egress:
          defaultPolicyAction: Allow
