label: apps/langgraph-demo
apps:
  - name: langgraph-demo
    description: "Langgraph agent application"
    subject:
      - - "@source:namespace=/"
        - "@org=acuvity.ai"
    tracing: Recording
    selector:
      type: Kubernetes
      kubernetes:
        kubernetesNamespace: langgraph-demo
    components:
      - name: ui
        description: "The UI running a React application."
        kind: Other
        selector:
          type: Kubernetes
          kubernetes:
            name: langgraph-demo-ui
            kubernetesNamespace: langgraph-demo
            type: Deployment
        egress:
          defaultPolicyAction: Allow
      - name: agent
        description: "The agent running the API server."
        kind: Agent
        selector:
          type: Kubernetes
          kubernetes:
            name: langgraph-demo
            kubernetesNamespace: langgraph-demo
            type: Deployment
        provider:
          category: App
          providerType: "LLM"
          hosts:
            - langgraph-demo-svc
            - langgraph-demo-svc.langgraph-demo
            - langgraph-demo-svc.langgraph-demo.svc.cluster.local
          extractors:
            - def:
                name: chat/request/message
                type: Input
                path: "/send"
                method: Post
                script: |-
                  function extract()
                    body = json.decode(input.body())
                    return {
                      extractions = { content = body.message },
                    }
                  end
            - def:
                name: chat/response/message
                type: Output
                path: "/send"
                method: Post
                script: |-
                  function extract()
                    body = json.decode(input.body())
                    return {
                      extractions = { content = body.output },
                    }
                  end
        egress:
          defaultPolicyAction: Allow
            
      - name: mcp-sequential-thinking
        description: "MCP Server: Sequential Thinking"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-sequential-thinking
            kubernetesNamespace: langgraph-demo
            type: Deployment
        provider:
          category: App
          providerType: "MCPServer"
          hosts:
            - mcp-server-sequential-thinking.langgraph-demo.svc.cluster.local
            - mcp-server-sequential-thinking.langgraph-demo
            - mcp-server-sequential-thinking
          extractors:
            - ref: mcp/input-http
            - ref: mcp/output-http
            - ref: mcp/output-http-get
            - ref: mcp/input-sse
            - ref: mcp/output-sse
        egress:
          defaultPolicyAction: Allow


      - name: mcp-brave-search
        description: "MCP Server: Brave Search"
        kind: Tool
        selector:
          type: Kubernetes
          kubernetes:
            name: mcp-server-brave-search
            kubernetesNamespace: langgraph-demo
            type: Deployment
        provider:
          category: App
          providerType: "MCPServer"
          hosts:
            - mcp-server-brave-search.langgraph-demo.svc.cluster.local
            - mcp-server-brave-search.langgraph-demo
            - mcp-server-brave-search
          extractors:
            - ref: mcp/input-http
            - ref: mcp/output-http
            - ref: mcp/output-http-get
            - ref: mcp/input-sse
            - ref: mcp/output-sse
        egress:
           defaultPolicyAction: Allow
