agent:
  image:
    repository: acuvity/google-adk-demo-agent
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 8300
  serviceType: ClusterIP
  corsOrigins: "*"
  config:
    agentModel: "anthropic/claude-sonnet-4-6"
  mcpServers:
    - name: mcp-server-sequential-thinking
      description: Sequential thinking MCP server
      url: "http://mcp-server-sequential-thinking.google-adk-demo.svc.cluster.local:8000/mcp"
    - name: mcp-server-brave-search
      description: Brave search MCP server
      url: "http://mcp-server-brave-search.google-adk-demo.svc.cluster.local:8000/mcp"
    - name: arcade-mcp-gateway
      url: https://api.arcade.dev/mcp/acuvity

  otel:
    enabled: true
    serviceName: "google-adk-demo-tracer"
    sendSpans: true
    consoleExport: true
    noFileExport: true
    file: "trace.log"
    otlpEndpoint: "http://127.0.0.1:4317"
    insecure: true

ui:
  image:
    repository: acuvity/google-adk-demo-ui
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 5174
  serviceType: ClusterIP
  backendUrl: "http://google-adk-demo-svc.google-adk-demo.svc.cluster.local"

litellm:
  apiKey: ""
  apiBase: "http://litellm.google-adk-demo.svc.cluster.local:4500"
  image: "docker.litellm.ai/berriai/litellm:main-stable"
  modelName: "claude-sonnet-4-6"
  model: "anthropic/claude-sonnet-4-6"


arcade:
  userId: ""

proxy:
  host: "ais-demo-gw.proofpoint-ais.svc.cluster.local"
  httpsPort: 443
  httpPort: 8080

secrets:
  anthropicApiKey: ""
  braveApiKey: ""
  arcadeApiKey: ""
  databricksHost: ""
  databricksAgentId: ""
  databricksToken: ""
  agentToken: ""
  litellmToken: ""

