apiVersion: v1
kind: Service
metadata:
  name: openai-sdk-demo-ui-svc
spec:
  selector:
    app: openai-sdk-demo-ui
  ports:
    - port: 80
      targetPort: {{ .Values.ui.port }}
  type: {{ .Values.ui.serviceType }}
